### ISSUE TITLE
install RstPreview ERROR:ImportError: No module named docutils.core

### ISSUE THREAD

**Issue by onestarshang** [d0ugal/RstPreview#24]
i installed docutils on win8, and there was an error:

error: RstPreview requires docutils to be installed for the python interpreter that Sublime uses.
    run: `sudo easy_install-2.6 docutils` and restart Sublime (if on Mac OS X or Linux). For Windows check the docs at
    https://github.com/d0ugal/RstPreview
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File ".\RstPreview.py", line 51, in run
  File ".\RstPreview.py", line 21, in rst_to_html
ImportError: No module named docutils.core

**Comment by d0ugal** [comment]
Unfortunately I'm not able to support windows, so I'm not sure why this is happening.

**Comment by onestarshang** [comment]
thanks for answering my question.

i think i will try it on linux, maybe it will work....

:)
