### ISSUE TITLE
Docutils Template Error

### ISSUE THREAD

**Issue by mattfarina** [d0ugal/RstPreview#9]
I'm now getting the error:

Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File "./RstPreview.py", line 64, in run
  File "./RstPreview.py", line 23, in rst_to_html
  File "./docutils/core.py", line 418, in publish_string
  File "./docutils/core.py", line 666, in publish_programmatically
  File "./docutils/core.py", line 223, in publish
  File "./docutils/writers/**init**.py", line 77, in write
  File "./docutils/writers/html4css1/**init**.py", line 174, in translate
  File "./docutils/writers/html4css1/**init**.py", line 177, in apply_template
IOError: [Errno 2] No such file or directory: 'docutils/writers/html4css1/template.txt'

When I try to preview the document up at https://raw.github.com/fabpot/Create-Your-Framework/master/book/part02.rst

**Comment by d0ugal** [comment]
Hmm. Have you updated? Based on that traceback it looks like its still using a local copy of docutils that has been removed now. There have been a few changes recently, so I'd delete it and install a fresh copy.

**Comment by mattfarina** [comment]
Very strange. I just tried to install it on a new system and after restarting ST2 something like 3 times it worked. Well, it seems to be working now. thanks.
